### ISSUE TITLE
using phyloNetworklm() with multiple records

### ISSUE THREAD

**Issue by richardreeve** [crsl4/PhyloNetworks.jl#101]
We're trying to estimate values of a trait for some tips of a tree, and we have a really simple model:

```julia
julia> fitTrait = phyloNetworklm(@formula(trait ~ 1), dat, tree)
```

with some tips set to `missing`, and using `ancestralStateReconstruction()` to recover the other tip values. If we put our mean trait estimates for each tip into the dataframe, then this all works fine, but it doesn't correctly characterise our uncertainty in the values of different tips. Instead, what we really have is a dataframe with lots of individual readings for each tip, and we'd like to put all of these values in - multiple trait values for each tip - just like we would in a non-phylogenetic linear model. At the moment is seemed to give an error about tipNames not matching, which is wrong. Is this actually possible?

**Comment by cecileane** [comment]
Variation within species isn't implemented at this point. You would need to have one tip per individual for this, with a single trait value per individual. All individuals from the same species would form a clade ("star" clade) in the larger phylogeny. The height of this clade (=length of branches to each individual in a given species) corresponding to the variance within that species. But the ratio between-species versus within-species variation is unknown and needs to be estimated. There are various ways to deal with this (when the phylogeny is a tree --straightforward to transfer to networks in theory). But we have not implemented any, at this point, sorry!

At this point, the closest you can get would be to use Pagel's λ model with a single value per species: add the option `model="lambda"` in the `phyloNetworklm` command. In theory, the within-species variation should be captured in the (1-λ) portion of the variance.

**Comment by richardreeve** [comment]
Okay, thanks. Are there any thoughts about adding this? It would be a very useful feature...

**Comment by cecileane** [comment]
Not at the moment. We need to find someone interested who has the time. But I agree, it would be a very useful feature. Not just useful --necessary I feel. It should be part of any future development for fitting a continuous response.

**Comment by cecileane** [comment]
woohoo, this feature was added (see #140) and is part of version 0.14.0 ! The main function was renamed to `phylolm`.

**Comment by richardreeve** [comment]
Ooh, that is exciting, we've actually submitted the paper that would have used it, but hopefully we'll find a way of using this soon!
