### ISSUE TITLE
Problem when analyzing choice of h

### ISSUE THREAD

**Issue by tangerzhang** [crsl4/PhyloNetworks.jl#111]
After get the results of SNAQ, I would like to determine the best h for hybridization events. Below are my commands:
```
using DataFrames
using PhyloNetworks
using Gadfly
using PhyloPlots
net0=readTopology("net0_bucky.out")
net1=readTopology("net1_bucky.out")
net2=readTopology("net2_bucky.out")
net3=readTopology("net3_bucky.out")
net4=readTopology("net4_bucky.out")
net5=readTopology("net5_bucky.out")
scores = [net0.loglik, net1.loglik, net2.loglik,net3.loglik,net4.loglik,net5.loglik]
using RCall
R"pdf"("score-vs-h.pdf", width=4, height=4);
R"plot"(x=0:5, y=scores, type="l", xlab="number of hybridizations h", ylab="network score");
R"dev.off"();
```
However, I got all of scores 0. 
```
julia> scores = [net0.loglik, net1.loglik, net2.loglik,net3.loglik,net4.loglik,net5.loglik]
6-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
```
This is odd because I've checked the net*_bucky.out and the -loglik values seems OK. I attached two network files and appreciate very much if you could help me out.
[net4_bucky.out.txt](https://github.com/crsl4/PhyloNetworks.jl/files/4065501/net4_bucky.out.txt)
[net5_bucky.out.txt](https://github.com/crsl4/PhyloNetworks.jl/files/4065503/net5_bucky.out.txt)

**Comment by cecileane** [comment]
Could you try to read in the output files with `readSnaqNetwork` instead of `readTopology`? It would look like this:
```julia
net0 = readSnaqNetwork("net0_bucky.out")
```
The function `readSnaqNetwork` is meant to read the score of the network after reading the network itself (for the network on the very first line of the file).

**Comment by tangerzhang** [comment]
This is really helpful! Thanks!
