### ISSUE TITLE
minor typo in documentation

### ISSUE THREAD

**Issue by crsl4** [crsl4/PhyloNetworks.jl#125]
In [multiple alleles](https://crsl4.github.io/PhyloNetworks.jl/latest/man/multiplealleles/#between-species-4-taxon-sets-1), the "weight of `1/(n_a n_b b_c n_c)`" should be "weight of `1/(n_a n_b n_c n_d)` ". I can make the change, but if someone is working on the documentation right now, let me know! I don't want to get in the way

**Comment by coraallensavietta** [comment]
Hi @crsl4, great catch! I'm in the middle of a PR and I'm happy to update this. How does this fix look? 
commit https://github.com/crsl4/PhyloNetworks.jl/pull/123/commits/cc467a4e50972b394681da9f2bf753a846d6e628:

**Comment by crsl4** [comment]
great, thanks!
