### ISSUE TITLE
How to use snp to do phylogenetic networks analysis using PhyloNetworks.jl?

### ISSUE THREAD

**Issue by xiekunwhy** [crsl4/PhyloNetworks.jl#130]
Hi,

If I have snps instead of gene sequences, how can I use PhyloNetworks to do phylogenetic networks analysis?

Best wishes,
Kun

**Comment by crsl4** [comment]
There is some recent work on estimating CF from SNPs ([paper](https://academic.oup.com/sysbio/article/doi/10.1093/sysbio/syaa005/5721377) and [R code](https://github.com/melisaolave/SNPs2CF)). Personally, I have not used these tools, but they seem like a nice option
