### ISSUE TITLE
multiple alleles: bug in mapAllelesCFtable?

### ISSUE THREAD

**Issue by cecileane** [crsl4/PhyloNetworks.jl#143]
@crsl4 : would you have time to look into this? I don't unfortunately...

See [google group question](https://groups.google.com/g/phylonetworks-users/c/jknHJARVMFU/m/eXR45eflAgAJ) and attached file, thanks to @brunoasm : it seems that `mapAllelesCFtable!` would return an empty list of repeated species, such that `mergeRows()` is not called during `readTableCF!` and the resulting `DataCF` object still has 13,757,814 4-taxon sets instead of a few 1000s:

```julia
CF = PhyloNetworks.mapAllelesCFtable("pnetworks_pops.txt","all_cf.csv") # 13,757,814 rows × 14 columns data frame
dataCF_summarized = PhyloNetworks.readTableCF!(CF) # DataCF, number of quartets: 13757814
```
yet `mergeRows` worked:
```julia
dataCF_summarized = PhyloNetworks.readTableCF!(PhyloNetworks.mergeRows(CF, [1,2,3,4,5,8,11,14]))# 2375 unique 4-taxon sets were found.
```

(used PhyloNetworks v0.11.0 and julia v1.5.1)

**Comment by crsl4** [comment]
Sorry, I cannot find the attached file. Can you forward it to me to be able to check?
I am spread too thin, but I'll try to carve out some time.
Thanks!

**Comment by cecileane** [comment]
The file is attached to the google group [question](https://groups.google.com/g/phylonetworks-users/c/jknHJARVMFU/m/eXR45eflAgAJ). It is not replicable (the data set is huge: 13,757,814 four-taxon sets), but I copy-pasted the key lines above. The problem is that `dataCF_summarized` still has 13,757,814 rows, instead of a few 1000s.

**Comment by brunoasm** [comment]
Hi @cecileane and @crsl4, thanks for looking into this!

Here I am attaching a subset of the data to reproduce the problem and help solving it. 
[pnetworks_test.zip](https://github.com/crsl4/PhyloNetworks.jl/files/5359453/pnetworks_test.zip)

I also added a row in which all alleles map to the same species. readTableCF!() removes that one, but does not average rows with same species.

Explicitly calling PhyloNetworks.mergeRows() does average over rows.
