### ISSUE TITLE
equal rates model fitdiscrete bug

### ISSUE THREAD

**Issue by coraallensavietta** [crsl4/PhyloNetworks.jl#147]
calling `fitdiscrete(net, :ERSM, species, dataframe; optimizeQ=false)

causes 2 problems:  
1. Error with PhyloNetworks v0.12.0 but not with v0.11.0    "ERROR: parameter k must be greater than or equal to 2" 

2. The model (and Q matrix) created have states  "abs" and "missing" instead of "pres" and "abs".
Missing should be interpreted as missing data, not as another category.

**Comment by cecileane** [comment]
1. This is a valid error: in case one of the 2 states is not observed. The error would be more helpful if the single label was printed out, to help the user.
2. This error was with v0.11.0. It does not appear in v0.12.0. `missing` values are correctly interpreted as missing by `learnlabels()` in v0.12.0.
