### ISSUE TITLE
performance suggestion make trees more type stable

### ISSUE THREAD

**Issue by oscardssmith** [crsl4/PhyloNetworks.jl#155]
If you use `Array{T<Anode,1}` instead of `Array{Anode}`, the performance should be much better as the `Array` will have a concrete type. I'm not sure how much this would help performance, but it should be a free win.

**Comment by cecileane** [comment]
Yes indeed. So `Edge` would be a parametric type then: `Edge{T}`. @crsl4 : this is worth a try, and see how it affects performance. After the concrete `Node` type is defined, we could define an `Edge()` constructor that creates an `Edge{Node}` by default. And other changes to avoid a big refactoring of the entire package.

**Comment by oscardssmith** [comment]
One way around this would be to define `EdgeT{T}` and then alias `Edge` to `EdgeT{Node}` once `Node` is defined.

**Comment by crsl4** [comment]
Yes, I agree! This is definitely worth trying to see how it affects performance. Are you in the midst of any changes so that you can add this, or do you prefer if I make this change on my end?

**Comment by cecileane** [comment]
There are 3 open pull-requests... so yes, definitely working on things. But `git` is here for us. You could make the changes on a branch, run examples locally to see how performance is affected, and then decide!

**Comment by crsl4** [comment]
sounds good!
