### ISSUE TITLE
Minor doc typo

### ISSUE THREAD

**Issue by crsl4** [crsl4/PhyloNetworks.jl#166]
In [Choosing the number of hybridizations](https://crsl4.github.io/PhyloNetworks.jl/stable/man/snaq_plot/#choosing-the-number-of-hybridizations), the X axis starts on 1, but it should start on 0 as the first point corresponds to `net0.loglik`.
Just documenting for now. Will fix it!

**Comment by cecileane** [comment]
fixed in v0.14.3
