### ISSUE TITLE
PhyloNetworks prevents BioSequences package upgrade

### ISSUE THREAD

**Issue by fpmenninger** [crsl4/PhyloNetworks.jl#168]
[BioSequences](https://github.com/BioJulia/BioSequences.jl) 3.0.0 released [06 Jan 2022](https://github.com/BioJulia/BioSequences.jl/releases/tag/v3.0.0)  

[Changed](https://github.com/BioJulia/BioSequences.jl/blob/master/CHANGELOG.md) from BioSequences 2.0.5
-  LongSequence is no longer copy-on-write. For views, use LongSubSeq.
-  Renamed LongAminoAcidSeq -> LongAA, LongNucleotideSeq -> LongNuc LongRNASeq -> LongRNA and LongDNASeq -> LongDNA
-  The interface for Alphabet and BioSequence is now more clearly defined, documented, and tested.
-  The constructor LongSequence{A}(::Integer) has been removed in favor of LongSequence{A}(undef, ::Integer).
-  Biological sequences can no longer be converted to/from strings and vectors.
-  Updated the element and substring search API to conform to Base.find* patterns.

## Current Behavior
```julia
(@v1.7) pkg> add PhyloPlots
    Updating registry at `E:\ProgramFiles\Julia\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
    Updating `E:\ProgramFiles\Julia\.julia\environments\v1.7\Project.toml`
  [7e6ae17a] ↓ BioSequences v3.0.0 ⇒ v2.0.5
  [c0d5b6db] + PhyloPlots v0.3.1
    Updating `E:\ProgramFiles\Julia\.julia\environments\v1.7\Manifest.toml`
  [621f4979] + AbstractFFTs v1.0.1
  [67c07d97] + Automa v0.8.2
  [13072b0f] + AxisAlgorithms v1.0.1
  [47718e42] + BioGenerics v0.1.1
  [7e6ae17a] ↓ BioSequences v3.0.0 ⇒ v2.0.5
  [3c28c6f8] ↓ BioSymbols v5.1.0 ⇒ v4.0.4
  [336ed68f] + CSV v0.9.11
```

**Comment by cecileane** [comment]
fixed in v0.14.3, which includes this commit a8155c8
