### ISSUE TITLE
Ghost introgression

### ISSUE THREAD

**Issue by JohnsonStev** [crsl4/PhyloNetworks.jl#192]
Hi,

I am wondering what phylonetworks will behave if the data contains introgression from unsampled lineages.
I have a data set that I suspect lineage A was introgressed with a ghost lineage.
When I ran phylonetworks on the data, the best supporting tree is the one that linked lineage A to the common ancestor of the two outgroups.
While this isn't possible because lineage A is a much younger than the outgroups, I am wondering if this provides some sort of support to the presence of ghost introgression?

Thanks

**Comment by crsl4** [comment]
Do you have a parenthetical format for your estimated network that you can share?

**Comment by cecileane** [comment]
Introgression from upsampled lineages can be detected, so long as they are "identifiable" (for SNaQ, that means creating a 'cycle' that is large enough, with at least 4 nodes). Some of the hybrid edges are expected to have positive (non-zero) lengths when one of the parent is a ghost (no sampled descendants).

SNaQ cannot estimate the root of the network: the output network should be interpreted as being "semi-directed", in the sense that the direction of edges below hybrid nodes is implied, but the exact root position is unknown. So if you find that a lineage A + the outgroups form a split, then there may be multiple possible positions for the root, which makes the interpretation is not straightforward. One of these positions may be compatible with a young age for A, but it's hard to tell without looking at the network.

You may be able to anonymize your network by changing the taxon names, like this for example if you have 40 or fewer taxa:
```julia
newnames = "t" .* string.(1:40)
anonymizednet = deepcopy(net); # replace 'net' by the variable that holds your network
for (i, tip) in enumerate(anonymizednet.leaf)
  tip.name = newnames[i]
end
writeTopology(anonymizednet) # shows taxon names t1,t2,t3, etc.
"(((t1:0.2,#H7:0.0::0.5):1.1,(((t2:...
```

**Comment by JohnsonStev** [comment]
Dear crsl4 and cecileane,

Thanks for the quick reply.
The tree I have is here:
((4_0,((1_0,(2_0,(3_0)#H7:::0.5034440738557908):0.014623648700821498):0.7315533554343951,#H7:::0.4965559261442092):0.7634213996734224):2.849640906290719,OG1_0,OG2_0);

**Comment by cecileane** [comment]
Here are a few ways to root your network: with the 2 taxa "OG1" and "OG2" as a clade, or as a grade, or as an outgroup clade with taxon "4". SNaQ cannot tell which one is most appropriate. External information is needed, about which taxa are outgroups. The code to replicate this figure is below.
[issue192_networkrooting.pdf](https://github.com/crsl4/PhyloNetworks.jl/files/10474873/issue192_networkrooting.pdf)

In any case, if the taxa named OG1/2 are the outgroups, then the reticulation shown in this network implies that there is a ghost lineage: a lineage along the edge numbered 8 in the figure (sister to the MRCA of taxa named 1,2,3), that left no descendants (extinct), or without any sampled descendants.

```julia
using PhyloNetworks, PhyloPlots, RCall

R"pdf"("issue192_networkrooting.pdf", 6, 6)
R"par"(mar=[0,0.1,0.5,0]);
R"layout"([1 2; 3 4]);

net = readTopology("((4_0,((1_0,(2_0,(3_0)#H7:::0.5034440738557908):0.014623648700821498):0.7315533554343951,#H7:::0.4965559261442092):0.7634213996734224):2.849640906290719,OG1_0,OG2_0);")

plot(net, showedgenumber=true, xlim=[1,8]);
R"mtext"("original network", side=3, line=-1, adj=0);

rootonedge!(net,10);
plot(net, showedgenumber=true, xlim=[1,9]);
R"mtext"("rooted on edge 10:\nmakes OG's a clade", side=3, line=-2, adj=0);

rootatnode!(net,"OG2_0");
plot(net, showedgenumber=true, xlim=[1,10]);
R"mtext"("rooted at OG2:\nmaking OG's a 'grade'", side=3, line=-1.5, adj=0);

rootonedge!(net,9);
plot(net, showedgenumber=true, xlim=[1,8]);
R"mtext"("rooted on edge 9:\nbring tip 4 sister to OG's", side=3, line=-1.5, adj=0);
R"dev.off"();
```
