### ISSUE TITLE
Inheritance Probability Confidence Interval?

### ISSUE THREAD

**Issue by bfauskee** [crsl4/PhyloNetworks.jl#198]
Hello,

I was wondering if there is anyway to calculate a confidence interval for gamma from bootstrap replicates. As far as I can tell, I don't believe this is an option in SNaQ. I understand I could extract gamma from each bootstrap replicate and calculate it manually, but I would have to manually check the topology of each replicate. Just wanted to see if anyone had suggestions on how to better go about this or if there is some option in SNaQ that I am missing.

Thanks!

**Comment by crsl4** [comment]
You can calculate mean and std with the info at the end of this section in the documentation, see [here](https://crsl4.github.io/PhyloNetworks.jl/stable/man/bootstrap/). I think that the `BSgam` object contains other values that you could use to find quantiles.

**Comment by bfauskee** [comment]
Thanks a ton! I must have missed that.
