### ISSUE TITLE
The confusion of starting topology

### ISSUE THREAD

**Issue by zhangwenda0518** [crsl4/PhyloNetworks.jl#204]
Hello, author, I have a puzzle
I have constructed a species tree by using nuclear genes, so can this species tree be used as the document of the starting topology?

And, what is the source of the starting topology? Is it a root tree?

Thanks！

**Comment by crsl4** [comment]
yes, the species tree can be the starting tree, and it does not need to be rooted. The starting tree is only used to help the optimization process. It is not kept fixed in any way.
