### ISSUE TITLE
Warning in topologyQPsedulik

### ISSUE THREAD

**Issue by ikkyle** [crsl4/PhyloNetworks.jl#21]
When I run `topologyQPseudolik!(guidetree, cf)`, the output below is all that I get. Prior to running, `net.loglik` was `0.0`, and it remains `0.0` after running this. 

`guidetree` is a `PhyloNetwork` network type read in using `readTopology` and cf is a `dataCF` type.

``` julia
julia> topologyQPseudolik!(guidetree, cf);
WARNING: 
    Using non-boolean collections with all(itr) is deprecated, use reduce(&, itr) instead.
    If you are using all(map(f, itr)) or all([f(x) for x in itr]), use all(f, itr) instead.
 in depwarn at deprecated.jl:73
 in nonboolean_all at deprecated.jl:803
 in all at reduce.jl:355
 in topologyQPseudolik! at /home/ikkyle/.julia/v0.4/PhyloNetworks/src/pseudolik.jl:1308
while loading no file, in expression starting on line 0
```

Using the same objects in `topologyMaxQPseudolik` works fine and successfully updates the `net.loglik` slot. 

Julia 0.4.0 (x86_64-linux-gnu) on Ubuntu 14.04, using the PhyloNetworks package version of about 30 minutes ago.

**Comment by crsl4** [comment]
Thanks Ian! I fixed it and it does not give problems to me anymore. Can you double check with your example and close this issue if everything is ok?

**Comment by ikkyle** [comment]
I triple checked that I cloned and rebuilt the PhyloNetworks package in a fresh session. Getting the error:

```
julia> topologyQPseudolik!(guidetree, cf);
WARNING: 
    Using non-boolean collections with all(itr) is deprecated, use reduce(&, itr) instead.
    If you are using all(map(f, itr)) or all([f(x) for x in itr]), use all(f, itr) instead.
 in depwarn at deprecated.jl:73
 in nonboolean_all at deprecated.jl:803
 in all at reduce.jl:355
 in topologyQPseudolik! at /home/ikkyle/.julia/v0.4/PhyloNetworks/src/pseudolik.jl:1308
while loading no file, in expression starting on line 0
ERROR: MethodError: `&` has no method matching &(::Function, ::Array{PhyloNetworks.Quartet,1})
Closest candidates are:
  &(::Any, ::Any, ::Any, ::Any...)
  &{S,T}(::Range{S}, ::AbstractArray{T,N})
  &{S,T}(::AbstractArray{S,N}, ::AbstractArray{T,N})
  ...
 in mapfoldl_impl at reduce.jl:42
 in mapfoldl at reduce.jl:62
 in nonboolean_all at deprecated.jl:805
 in all at reduce.jl:355
 in topologyQPseudolik! at /home/ikkyle/.julia/v0.4/PhyloNetworks/src/pseudolik.jl:1308
```

**Comment by crsl4** [comment]
Can you provide your guidetree and cf? I cannot replicate the error message. When I run the function with different examples, I don't get any error.

**Comment by ikkyle** [comment]
Github won't let me attach the files here. I'll email them to you.

**Comment by crsl4** [comment]
Hi Ian, I cannot replicate the error:S
I do:
using PhyloNetworks
d=readTableCF("quartetCF.csv");

tree = readTopologyLevel1("tree.tre");
topologyQPseudolik!(tree,d)
16713.306166320337

or

tree2 = readTopology("tree.tre");
topologyQPseudolik!(tree2,d)
16713.306166320337
