### ISSUE TITLE
bucky.pl error "Insufficient list members"

### ISSUE THREAD

**Issue by JOSEJMOVI** [crsl4/PhyloNetworks.jl#40]
I'm following the PhyloNetworks workshop using some alignments of coding sequences from my transcriptomes. When using the script bucky.pl this error "Insufficient list members at scripts/bucky.pl line 1407." is displayed. I'm using 127 single copy genes from 30 species and not all species are represented in all the alignments. Also, species IDs are four letters strings. I wonder what I'm doing wrong  :)

**Comment by crsl4** [comment]
Yes, I suspect that this could be the problem. The `bucky.pl` script assumes that all species are represented in all alignments, see the [post in the google group](https://groups.google.com/forum/#!topic/phylonetworks-users/AtnJfUZI_lo).

SNaQ is able to handle your situation in which not all species are represented in all alignments, but unfortunately our `bucky.pl` script does not allow for this and you would need to modify this script.

**Comment by JOSEJMOVI** [comment]
Ahh thanks for the quick answer. I will follow the google group from now on

**Comment by crsl4** [comment]
Thanks. Sorry I cannot be more helpful at this point. Our collaborator that wrote the `bucky.pl` script is no longer working on this project. We definitely want to modify this script to allow for missing data, but we have not had the time to do so:(
But we welcome any contribution! If you are interested in modifying this script, you can fork the repository for [TICR](https://github.com/nstenz/TICR) and we can pull all your changes.
