### ISSUE TITLE
in docs: broken link to lizard tree & traits

### ISSUE THREAD

**Issue by cecileane** [crsl4/PhyloNetworks.jl#42]
I noticed that we need to change the link to the lizard tree to this:
https://github.com/crsl4/PhyloNetworks.jl/blob/master/examples/lizard_tree.txt
in this doc file: `docs/src/man/trait_tree.md`, first paragraph.

The link to the lizard traits is also broken, that's in the same file `trait_tree.md` but near the end, "Phylogenetic ANOVA" section. The correct link is this: https://github.com/crsl4/PhyloNetworks.jl/blob/master/examples/lizard_trait.txt

Paul @pbastide: would you mind add this to one of your next commit?

**Comment by pbastide** [comment]
Thank you Cécile for the correct links!
I fixed it in y master branch, so I think the issue will be closed automatically in the next merge.
