### ISSUE TITLE
isMajor not correct after reading a network

### ISSUE THREAD

**Issue by cecileane** [crsl4/PhyloNetworks.jl#44]
## example 1: both minor

In the example below, the γ's don't sum up to 1.0 and `isMajor` is not set accordingly:
```julia
using PhyloNetworks
net21 = readTopology("(A,((B,#H1),(C,(D)#H1:::0.2)));")
printEdges(net21)
```
we get get this output, where (D) is missing in the parenthetical description, last line:
```
PhyloNetworks.HybridNetwork, Rooted Network
9 edges
9 nodes: 4 tips, 1 hybrid nodes, 4 internal tree nodes.
tip labels: A, B, C, D
(A,((B,#H1),(C,#H1:::0.2)));
```
It's because both hybrid edges are set to minor, which causes `writeTopology` to not descend below the hybrid edge:

```julia
julia> printEdges(net21)
Edge	Node1	Node2	InCycle	containRoot	istIdentitiable	Length	isHybrid	Gamma	isMajor
1	1	-2	-1	true		false		NA	false		1.0	true
2	2	-4	-1	true		false		NA	false		1.0	true
3	-4	3	-1	false		false		NA	true		-1.0	false
4	-4	-3	-1	true		true		NA	false		1.0	true
5	4	-5	-1	true		false		NA	false		1.0	true
6	5	3	-1	true		false		NA	false		1.0	true
7	3	-5	-1	false		true		NA	true		0.2	false
8	-5	-3	-1	true		true		NA	false		1.0	true
9	-3	-2	-1	true		true		NA	false		1.0	true
```
The γ's aren't in sync, so it's a worry for deleting hybrid edges below some threshold:
```julia
julia> deleteHybridThreshold!(net21,0.5) |> writeTopology
"(A,((B,D),C));"

julia> printEdges(net21)
Edge	Node1	Node2	InCycle	containRoot	istIdentitiable	Length	isHybrid	Gamma	isMajor
1	1	-2	-1	true		false		NA	false		1.0	true
2	2	-4	-1	true		false		NA	false		1.0	true
4	-4	-3	-1	true		true		NA	false		1.0	true
5	4	-3	-1	true		false		NA	false		1.0	true
6	5	-4	-1	true		false		NA	false		1.0	true
9	-3	-2	-1	true		true		NA	false		1.0	true
```
## example 2: both major

Another case with a similar bug: here the γ's are correct (because good input), but both are 0.5 and both hybrid edges are turned major. The one near the leaf node should be made minor:

```julia
julia> net22 = readTopology("(A,((B,#H1:::0.5),(C,(D)#H1:::0.5)));")
```
we get this, where the newick format is incorrect because `writeTopology` descend below the hybrid edge twice, once for each hybrid edge (both major), so `(D)` appears twice:
```
PhyloNetworks.HybridNetwork, Rooted Network
9 edges
9 nodes: 4 tips, 1 hybrid nodes, 4 internal tree nodes.
tip labels: A, B, C, D
(A,((B,(D)#H1:::0.5),(C,(D)#H1:::0.5)));
```

This could be quite dangerous with multiple hybrids. Now to see that both hybrid edges are major, and that it causes an error if we want to delete the hybrid:

```julia
julia> printEdges(net22)
Edge	Node1	Node2	InCycle	containRoot	istIdentitiable	Length	isHybrid	Gamma	isMajor
1	1	-2	-1	true		false		NA	false		1.0	true
2	2	-4	-1	true		false		NA	false		1.0	true
3	-4	3	-1	false		false		NA	true		0.5	true
4	-4	-3	-1	true		true		NA	false		1.0	true
5	4	-5	-1	true		false		NA	false		1.0	true
6	5	3	-1	true		false		NA	false		1.0	true
7	3	-5	-1	false		true		NA	true		0.5	true
8	-5	-3	-1	true		true		NA	false		1.0	true
9	-3	-2	-1	true		true		NA	false		1.0	true

julia> deleteHybridThreshold!(net22,0.5);
ERROR: type Void has no field gamma
 in deleteHybridThreshold!(::PhyloNetworks.HybridNetwork, ::Float64) at /Users/ane/.julia/v0.5/PhyloNetworks/src/compareNetworks.jl:233
```

## checks to add?

To me, it looks like `readTopology` should comply with this:
-  if γ1=γ2 (=0.5 or whatever other value), do *not* set both `isMajor` to true.
-  if γ1 and γ2 < 0.5, do *not* set both `isMajor` to false (minor).
- select the leaf to be minor if both γ's are missing, or both are equal
- re-scale the γ's if their sum is not approximatively 1.0

These things are done in `cleanAfterReadAll!(net,leaveRoot)` inside  `readTopologyUpdate`, but not in `readTopology`.

To fix this issue, it might be also safe to check `setGamma()`. Currently, this function sets `isMajor=true` for γ>0.5 or γ>=0.5. This behavior might need to be changed to *not* update `isMajor` if γ=0.5 (approximately).

**Comment by cecileane** [comment]
tagging @ChristianBorst!

**Comment by pbastide** [comment]
I was about to open an other issue, but then I realized it was linked with this one (exemple 2).
When a hybrid inherits 50-50 from both its parents, then the `plot` function throws an error:
```julia
julia> net = readTopology("((A:0.3,(B:0.3)#H1:0::0.5):0.7,(#H1:0.4::0.5,C:0.7):0.3);")
julia> plot(net, :RCall)
ERROR: hybrid node 3 has 0 or 2+ major hybrid parents
Stacktrace:
 [1] #directEdges!#415(::Bool, ::Function, ::PhyloNetworks.HybridNetwork) at /home/bastide/.julia/v0.6/PhyloNetworks/src/manipulateNet.jl:662
 [2] getEdgeNodeCoordinates(::PhyloNetworks.HybridNetwork, ::Bool) at /home/bastide/.julia/v0.6/PhyloNetworks/src/plotsGadfly.jl:11
 [3] #plot#494(::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}}, ::ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}}, ::ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}}, ::Bool, ::Bool, ::DataFrames.DataFrame, ::DataFrames.DataFrame, ::Gadfly.#plot, ::PhyloNetworks.HybridNetwork) at /home/bastide/.julia/v0.6/PhyloNetworks/src/plotsGadfly.jl:307
 [4] plot(::PhyloNetworks.HybridNetwork) at /home/bastide/.julia/v0.6/PhyloNetworks/src/plotsGadfly.jl:307
```
Taking 0.51-0.49 instead, the problem disappears:
```julia
julia> net = readTopology("((A:0.3,(B:0.3)#H1:0::0.51):0.7,(#H1:0.4::0.49,C:0.7):0.3);")
julia> plot(net, :RCall)
```
The error seems to be issued by [`directEdges!`](https://github.com/crsl4/PhyloNetworks.jl/blob/39a2375f8ad34607023b678b8692b2cc7cc55e09/src/manipulateNet.jl#L650), that relies on the `isMajor` attribute (both edges are marked as "major" here in the 50-50 case).

So maybe an other reason to deal with this !

**Comment by crsl4** [comment]
Thanks Paul! Yes, we have this issue because `readTopology` does not check that things are consistent in a network. Checks are done at the end of `readTopologyLevel1` which is meant to hava a network ready as starting point for SNaQ estimation. However, `readTopology` does not have checks yet. I believe this is something that @ChristianBorst is working on.

**Comment by nkarimi** [comment]
I also had similar issues when summarizing bootstrap networks. One network had a hybrid with a 50-50 inheritance from both parents, but this wasn't clear from the errors.  

Errors below and how it was identified:
`julia> bestnet = readTopology("best_network.out")`
`julia> bootnet= readMultiTopology("bootstrap_networks.out")
100-element Array{PhyloNetworks.HybridNetwork,1}:
 PhyloNetworks.HybridNetwork, Rooted Network`

`julia> BSe_tree= treeEdgesBootstrap(bootnet, bestnet)
ERROR: type Void has no field gamma
 in deleteHybridThreshold!(::PhyloNetworks.HybridNetwork, ::Float64) at /u/n/i/nisa/.julia/v0.5/PhyloNetworks/src/compareNetworks.jl:233
 in displayedTrees(::PhyloNetworks.HybridNetwork, ::Float64) at /u/n/i/nisa/.julia/v0.5/PhyloNetworks/src/compareNetworks.jl:279
 in majorTree at /u/n/i/nisa/.julia/v0.5/PhyloNetworks/src/compareNetworks.jl:292 [inlined]
 in treeEdgesBootstrap(::Array{PhyloNetworks.HybridNetwork,1}, ::PhyloNetworks.HybridNetwork) at /u/n/i/nisa/.julia/v0.5/PhyloNetworks/src/bootstrap.jl:499`

`julia> BSn, BSe, BSc, BSgam, BSedgenum = hybridBootstrapSupport(bootnet,bestnet);
ERROR: hybrid node 19 has 0 or 2+ major hybrid parents
 in #directEdges!#411(::Bool, ::Function, ::PhyloNetworks.HybridNetwork) at /u/n/i/nisa/.julia/v0.5/PhyloNetworks/src/manipulateNet.jl:662
 in #hybridBootstrapSupport#436(::Bool, ::Function, ::Array{PhyloNetworks.HybridNetwork,1}, ::PhyloNetworks.HybridNetwork) at /u/n/i/nisa/.julia/v0.5/PhyloNetworks/src/bootstrap.jl:851
 in hybridBootstrapSupport(::Array{PhyloNetworks.HybridNetwork,1}, ::PhyloNetworks.HybridNetwork) at /u/n/i/nisa/.julia/v0.5/PhyloNetworks/src/bootstrap.jl:707`

Then use the following to identify which network had the 50:50 inheritance. 
`for i in 1:100 @show i; treeEdgesBootstrap(bootnet[i:i],bestnet); end
i = 1`

`writeTopology` also returned errors when attempting to read this individual network.

Then use `setGamma!` to change the major hybrid edge to inheritance gamma of .500000000001.  The minor hybrid edge changes automatically to 0.499999999999
