### ISSUE TITLE
change confidence level for prediction intervals

### ISSUE THREAD

**Issue by cecileane** [crsl4/PhyloNetworks.jl#57]
@pbastide, could the function `ancestralStateReconstruction` have an argument to vary the level of confidence --for example to 90%?

**Comment by cecileane** [comment]
or perhaps just an example in the doc that could show how to get a t-value (and then use it)? @rkriebel and I wanted to get 90% CIs.

**Comment by pbastide** [comment]
The `ancestralStateReconstruction` function produces an object `ReconstructedStates`.
By default, when showed, this object displays 95% prediction intervals.

However, other confidence levels can be retrieved, using functions [`predint`](http://crsl4.github.io/PhyloNetworks.jl/stable/lib/public/#PhyloNetworks.predint) (or [`predintPlot`](http://crsl4.github.io/PhyloNetworks.jl/stable/lib/public/#PhyloNetworks.predintPlot) for a plot).
The optional argument is `level`, the same as in GLM's [`confint`](https://github.com/JuliaStats/GLM.jl/blob/dbad91a9598659380853b042e231af63b86f38d5/src/glmfit.jl#L138).

Is that what you had in mind ? It is already documented in the library. Should we add an example in the man page ?

**Comment by cecileane** [comment]
I see, thank you, this is fantastic.

I didn't see it documented in the manual. We looked at the documentation for `ancestralStateReconstruction` (which does show 95% intervals to the screen), but we didn't think about looking into options for `predint` or `predintPlot`. It could be useful to have the option `level=0.90` used in one of the examples in the manual, like [here](https://github.com/crsl4/PhyloNetworks.jl/blob/master/docs/src/man/src/trait_tree.jmd#L169) for instance, or add some text after [here](https://github.com/crsl4/PhyloNetworks.jl/blob/master/docs/src/man/src/trait_tree.jmd#L120) to talk about how one might change the confidence level. Just an idea.
