### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by tangerzhang** [crsl4/PhyloNetworks.jl#69]
Could you please show me how the parallelization works for PhyloNetworks?
For example, I am going to run the following command lines:
net0 = snaq!(tre,buckyCF,hmax=0, filename="snaq/net0_bucky",runs=100)
net1 = snaq!(net0,buckyCF,hmax=1, filename="snaq/net1_bucky",runs=100)
net2 = snaq!(net1,buckyCF,hmax=2, filename="snaq/net2_bucky",runs=100)
How can I split the command lines for each run and submit jobs to a cluster?
Thanks!

**Comment by cecileane** [comment]
You first need to tell Julia to use multiple processors, with the `addprocs` command. For example: `addprocs(10)` if your machine has 10 or more processors. Then tell all the processors about the packages and functions to be used, with `@everywhere using PhyloNetworks`. Then you can run your `snaq!` commands. They will check how many processors are available to Julia, and will use them all automatically. These processors need to be on the same machine, however, not on separate machines.

The tutorial explains this [here](http://crsl4.github.io/PhyloNetworks.jl/latest/man/snaq_plot/#parallel-computation).

**Comment by tangerzhang** [comment]
Got it! Thanks!
