### ISSUE TITLE
phylogeny parsing: error when a hybrid node has hybrid child

### ISSUE THREAD

**Issue by cecileane** [crsl4/PhyloNetworks.jl#70]
In this situation, the network is not of level 1, but the `readTopology` function should still be able to parse the network. The issue was reported on the [google group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/phylonetworks-users/2GWULTOcF9U). Examples:
```julia
net = readTopology("((((B)#H1)#H2,((C,#H2)S1,(#H1,A)S2)S3)S4);")
```
    ERROR: hybrid node 3 has more than two hybrid edges attached to it: polytomy that cannot be resolved without intersecting cycles.

doing this helps to see that the parenthetical description is just fine (the # signs were taken out to mean that node names are just normal names):

```julia
net = readTopology("((((B)H1)H2,((C,H2)S1,(H1,A)S2)S3)S4);")
plot(net, showNodeNumber=true)
net.node
```

Another example:

```julia
net = readTopology("((A,(((B,C))#H1)#H2),(#H2,((#H1,D),E)));") # error: node 5 has >2 hybrid edges
net = readTopology("((A,(((B,C))H1)H2),(H2,((H1,D),E)));")   # just fine
plot(net, showNodeNumber=true) # to see what the network was supposed to be
net.node
```

@ChristianBorst: we can work on this after your improvements to the parsing functions are merged into the master version.

**Comment by cecileane** [comment]
this network can be parsed, so the problem is not about one node having 2 hybrid children:
```julia
net = readTopology("(((A,(B)#H1),((C)#H2,#H1)),(D,#H2));")
```

**Comment by cecileane** [comment]
same problematic network as above: the error goes away if we pretend that H3 is not a hybrid node (i.e. leaving it as 2 separate nodes by removing the # sign in front of its name). No problem with this:
```julia
net = readTopology("((((((((((((((Ae_ca1,Ae_ca2),Ae_ca3))#H1,#H2),(((Ae_um1,Ae_um2),Ae_um3),#H1)),((Ae_co1,Ae_co),(((Ae_un1,Ae_un2),Ae_un3),Ae_un4))),(((Ae_ta1,Ae_ta2),(Ae_ta3,Ae_ta4)),((((((((Ae_lo1,Ae_lo2),Ae_lo3),(Ae_sh1,Ae_sh2)),((Ae_bi1,Ae_bi2),Ae_bi3)),((Ae_se1,Ae_se2),Ae_se3)))#H2,H3),#H4))),(((T_bo1,(T_bo2,T_bo3)),T_bo4),((T_ur1,T_ur2),(T_ur3,T_ur4)))),(((((Ae_sp1,Ae_sp2),Ae_sp3),Ae_sp4))H3,((((Ae_mu1,Ae_mu2),Ae_mu3),Ae_mu4))#H4))),Ta_ca),S_va),Er_bo),H_vu);");
plot(net, showIntNodeLabel=true)
```

**Comment by ujain6** [comment]
In the readTopology function, there are some lines which I'm not sure what are they doing.
net = HybridNetwork( )
and 
n = Node(-1*numLeft[1], false).

**Comment by crsl4** [comment]
`net = HybridNetwork( )` creates an empty `HybridNetwork` object, and `n = Node(-1*numLeft[1], false)` creates an object `Node` that is not a leaf (hence the second argument false) and with number `-1*numLeft[1]`. The node number was chosen to be negative for internal nodes, and it depends on the number of left parenthesis that have been read from the parenthetical format so far.

**Comment by ujain6** [comment]
Hi Cecile, I'm still trying to pinpoint where the error might be coming from. But for that, I just wanted to clarify that whenever we're parsing a string with hybrid nodes (that are separated into a leaf node and a node of their own with major and minor edges), do we want to plot the network by merging those two  nodes (so that the hybrid node has two edged pointing to it now), or do we just acknowledge this information and add the results to the appropriate lists?

**Comment by cecileane** [comment]
yes, we do want to merge the 2 nodes labelled "#H1" (say). When the string is read, we have to create 2 nodes, but as soon as the second node is created, we should recognize that this second node should merged with the first one that had the same label. Once the full string is parsed, there should be a single node per reticulation: and yes, this node would have 2 incoming parent edges pointing to it.

**Comment by ujain6** [comment]
I installed the Julia extension to Visual Studio, but can't find the setting where I can set the executable to point to Julia. Because of this, I get an error "Julia language server is busy". Do you know where can I set the path?

**Comment by cecileane** [comment]
The instructions [here](
https://marketplace.visualstudio.com/items?itemName=julialang.language-julia) worked for me.

When I go to Code -> Preferences -> Settings, VS Code opens my user setting file, which has this currently:
```
{
    "julia.executablePath": "/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia",
    "markdown-pdf.convertOnSave": false,
    "markdown-pdf.format": "letter",
    "markdown-pdf.border.top": "0.5in",
    "markdown-pdf.border.bottom": "0.5in",
    "markdown-pdf.border.right": "0.5in",
    "markdown-pdf.border.left": "0.5in",
}
```
The first line is used to give a pointer to the julia executable (you can safely ignore all the lines to set markdown-pdf preferences).

**Comment by ujain6** [comment]
When we call the parseHybridNode method on a node with the # sign and find out that it is the first hybrid node we're encountering, we mark it a leaf depending upon whether the edge is a major or a minor, right?

And then we create a hybrid edge between the node with the # sign and it's parent. Am I inferring this in the right way?

**Comment by cecileane** [comment]
here is a much smaller -so easier- example to work with. I just trimmed the larger example down to have fewer tips and fewer hybridizations.

Below: `net1` reproduces the error with message "both hybrid nodes are internal nodes: ...".
`net2` is the same as `net1`, except that it has `#H3` changed to `H3` and does *not* cause an error, like before.

```julia
net1 = readTopology("(((lo,#H3),#H4),((sp)#H3,(mu)#H4));"); # error
net2 = readTopology("(((lo, H3),#H4),((sp) H3,(mu)#H4));"); # no error
plot(net2, showIntNodeLabel=true, showNodeNumber=true)
```

If we change the order in which clades are entered, however, the error disappears! below: `net3` has the exact same topology as `net1`, but written in a different order: with the "sp+mu" clade written first instead of second, and "lo" coming second instead of first.

```julia
net3 = readTopology("(((sp)#H3,(mu)#H4),((lo,#H3),#H4));"); # no error!
plot(net3, showIntNodeLabel=true, showNodeNumber=true)
```

hopefully things can be diagnosed more easily on this example.

**Comment by ujain6** [comment]
Hi Cecile,

in net1, (sp)#H3 means that H3 has a single child that is "sp"? Right?
