### ISSUE TITLE
Gene too short for RAxML + Astral analysis?

### ISSUE THREAD

**Issue by marybelsoto** [crsl4/PhyloNetworks.jl#78]
Hi there,

I successfully ran RAxML and ASTRAL for 263 out of 264 genes using the raxml.pl script provided here. The gene for which there was no output (no best tree or bootstrap replicates) is 234 bp long. Is there a length cutoff somewhere along this analysis? I tried running the gene on its own and got no output again.

Thanks in advance. Best,
Marybel

**Comment by cecileane** [comment]
Hi Marybel,
There is no such threshold on the alignment length. It might be some other thing that RAxML doesn't like. Could you try and run RAxML on this particular alignment on its own, outside of the `raxml.pl` script, to see what message RAxML gives you?

**Comment by marybelsoto** [comment]
Hi Cécile,

Thanks for your reply. I ran RAxML outside of the script and there didn't seem to be any issues with the gene (info file attached). I used the same commands as in the script (-T 2 -m GTRGAMMA -f a -N 100 -p 9810 -x 3691 -s 205.trimmed.phy -n 205.out). I wonder what's going on...

[RAxML_info.205.txt](https://github.com/crsl4/PhyloNetworks.jl/files/2076968/RAxML_info.205.txt)

Thanks for any additional thoughts you may have on this.

**Comment by cecileane** [comment]
sorry this is an old thread. I cannot spot any obvious reason for why the `raxml` script skipped this one gene. Perhaps there were permission issues when the script needed to write new files (like the trimmed alignment with a single representative of the duplicate sequences, or any of the output files), like if some user quota was reached? Also, RAxML would fail if it's being asked to overwrite an existing file. I can't find any red flags.
