### ISSUE TITLE
standardize getter names?

### ISSUE THREAD

**Issue by cecileane** [crsl4/PhyloNetworks.jl#80]
What do you think about changing the names of 'getters', based on this [discussion](https://github.com/BioJulia/Phylogenies.jl/issues/1)? It's a long thread, but example names are [here](https://github.com/BioJulia/Phylogenies.jl/issues/1#issuecomment-350424028) or [here](https://github.com/BioJulia/Phylogenies.jl/issues/1#issuecomment-349110217). In particular, we could use these names to be consistent with other packages like BioJulia [Phylogenies](https://github.com/BioJulia/Phylogenies.jl/blob/master/src/Phylogenies.jl): `isleaf(node)`, `root(net)`, `parent(edge)`, `child(edge)`, `children(node)`, `hasparent()` etc.

Currently, we have `getChild(edge)`, `getChildren(node)`, [`getParent(edge)`](http://crsl4.github.io/PhyloNetworks.jl/latest/lib/internals/#PhyloNetworks.getParent-Tuple{PhyloNetworks.Edge}), `getParents(node)`, `getPartner(edge)`, `getMajorParent(node)`, `getMinorParent(node)`, `getMajorParentEdge(node)`, `getMinorParentEdge(node)`, and some undocumented ones like `getMajorParentEdgeNumber` (I thought I saw others, but can't find them now).

I would like to have another one `getSibling()`. A more standard name should be just `sibling()`, but that would be departing from our current name convention. What do you think about changing all of our 'getters' names? I can volunteer to do it (some time in the future, not now). A main hurdle is that the names `parent` and `child` or `children` are currently being used to define variables. Those would need to be changed first, to avoid re-defining a `parent()` function (say) within a block. Thanks for your thoughts!

**Comment by crsl4** [comment]
Hi Cecile, 
Yes, it is a good idea!! I have no problem with this at all.
Also, I am sure that we have `getSibling` already, although it has a different name that I don't recall (as you know, my function names are not the most intuitive).
Claudia

**Comment by pbastide** [comment]
I agree, it would be a good idea to unify the function names across Julia phylogenetic packages.
Mirroring the names of BioJulia Phylogenies seems a good first step toward a common interface. I'm not sure it's related, but I also came across this [AbstractTrees](https://github.com/Keno/AbstractTrees.jl) package, that implements a `children` method too.

About the "trait-based" approach, maybe the package [SimpleTraits](https://github.com/mauro3/SimpleTraits.jl) could be a way to go ? It's not part of the Julia Base, but seems to be well maintained.

To add to our list, there could be also [`getHybridEdge`](https://github.com/crsl4/PhyloNetworks.jl/blob/e29fc38af44d0981b33fd90abead96540bf4a1bd/src/auxiliary.jl#L391) and `getConnectingEdge`. I also noticed two functions that seem to be doing very similar things: [`getNodeAges`](https://github.com/crsl4/PhyloNetworks.jl/blob/d5fe6dedf7bef091321fa8f9e07ed4512f2d5603/src/pairwiseDistanceLS.jl#L21), and the undocumented [`getHeights`](https://github.com/crsl4/PhyloNetworks.jl/blob/de0eb43352a1e29920bfdd4d39e939c19c25b86f/src/traits.jl#L1180).

**Comment by cecileane** [comment]
Wow, I didn't know about `getHeights`. cool function. Some time ago, I changed the documentation, to include any internal function that has a docstring. It makes functions a tiny bit more discoverable, through the list in the documentation. (For exported functions, we still have to list each one individually to have its docstring appear in the documentation). So when you come across an internal function with no docstring, it's a useful investment to write docstring! (unless you don't trust the function).

`getNodeAges` makes assumptions about the network, if I remember well: that it's time consistent, and all tips sampled at time 0 (present). Such information would be good to have in a docstring, if we want to have a good set of "getter" functions. A better name would be `nodeages` instead, perhaps.

**Comment by pbastide** [comment]
Duly noted about the docstring for internal functions ! I'll keep it in mind.

Actually, now that you mention it, both functions are not doing exactly the same thing, as `getHeights` assumes that the root is at time t=0. It still needs a time consistent network, but it should work with a non ultrametric network (i.e. all tips do not need to be at the same distance from the root). Its `ape` equivalent would be `node.depth.edgelength`, I think.

**Comment by cecileane** [comment]
So, if/when we unify getter names, `getHeights` (or a modification of it) could be renamed `nodedepth` and have an option `edgelength` = true or false (or `useEdgeLength` for the option, like in `plot`).
Well, perhaps not: in the math literature, the depth is typically defined as being 0 for the leaves, not root, unless I am mistaken. Something to think through carefully. Other options in `ape` are `dist.nodes()` and `branching.times()`

@RC0515 is currently needing a way to check if a network is time-consistent, to make the network time-consistent if so desired, to get the height of each node (distance to the root, defined perhaps via the major path when the network is not time-consistent), and then to fill in the missing branch lengths of external edges to make the network ultrametric. (we get those missing edge lengths when we infer a network with `snaq!`, but later we need branch lengths on all edges to do simulations). For now, thanks for the pointer to `getHeights`, @pbastide!

**Comment by cecileane** [comment]
I'm about to tackle this. So please chime in!

For consistency with [PhyloTrees](https://github.com/jangevaare/PhyloTrees.jl/blob/master/src/PhyloTrees.jl), we would replace `getParent` by `parentnode`, which we could then extend to take as input either an edge (most typically), or a node. Similarly, replace `getChild` by `childnode`. I like that the name says very explicitly if we are getting a node vs an edge. It is *not* the case of our current accessor names. For example we have `getParent(edge)`, `getParents(node)`, `getMajorParent(node)` and `getMinorParent(node)` to get a node, then `getMajorParentEdge(node)` and `getMinorParentEdge(node)` to get an edge. We also have `getChild(edge)`, `getChildEdge(node)` and `getChildren(node)`. We could bring some uniformity to this zoo of names.

However, the names from `PhyloTrees.jl` are "simple" and, in fact, used as variable names, even in the package itself. They could cause conflict for users too. So we could instead prefer action names like `get_parentnode` and `get_childnode`, or `getparentnode` and `getchildnode`. In that case, we would not have consistent names with that in `PhyloTrees.jl`, but I think it's more important to get a good API for users.

By the way, these "getters" are not exported, so far. After we settle on good names, we can export them.

The old function names can be deprecated if we wish, so they continue to be usable. (Although deprecation warnings don't appear for users by default, unless I'm mistaken). I am *not* in favor of adding them as deprecated, because it would cause them to be exported (I think), and most of these functions are not exported so far. So I consider this change as internal, and deprecations not needed.

We would need to bump the minor version number (to v0.16.x) to indicate a breaking change in API. Packages that depend on `PhyloNetworks` and have the current version in their compatibility section (as they should) would not be affected. The developers would have to change the variables names and them bump their compat section.

**Comment by crsl4** [comment]
personally, I prefer the action names like `getparentnode` and `getchildnode`. We could keep the other functions internal and deprecated (internally). Would a warning with a deprecated message be enough?

**Comment by cecileane** [comment]
Thanks!

> I prefer the action names like `getparentnode` and `getchildnode`.

That's the approach I've started to take on the [dev](https://github.com/crsl4/PhyloNetworks.jl/tree/dev) branch. Except that I use `getparent` `getchild` etc. to get a node, and `getparentedge` etc to get an edge. See [here](https://github.com/crsl4/PhyloNetworks.jl/blob/dev/src/PhyloNetworks.jl#L74) for example, for a list of names.

> We could keep the other functions internal and deprecated (internally)

Yes, it looks like @deprecate has an option to avoid exporting the old name, if the new name is exported.

> Would a warning with a deprecated message be enough?

By default, users do *not* see deprecation warnings. These warnings appear when testing a package: it tells the package developer of any deprecations from dependencies.

**Comment by crsl4** [comment]
I meant an artificial deprecation warning as `@warn "Deprecated function!"`. But I agree with using `@deprecate`.

**Comment by cecileane** [comment]
I see, thanks. I would have to learn how to do this.

Otherwise, it's as simple as adding this to file `deprecated.jl`:
```julia
@deprecate getChild getchild false
```
where option `false` is to *not* export `getChild` even is `getchild` is exported.
Users would get the warning if they started julia with `julia --depwarn=yes`. But not by default, because the default flag is `depwarn=no` (except when running tests).
