### ISSUE TITLE
error with Julia v1.0

### ISSUE THREAD

**Issue by MeiyuanJi** [crsl4/PhyloNetworks.jl#83]
I am a beginner of Julia and for using this program, I installed Julia the first time. 
After I had Julia installed, and got into it, typing 
Pkg.add("PhyloNetworks") as in the tutorial
it encountered some problem as blow
![default](https://user-images.githubusercontent.com/33933620/44457055-c9443200-a634-11e8-99f8-5b3449356117.png)
I figured this problem by typing
Pkg.build("CodecZlib")
Howerver, when I inputed 
using PhyleNetworks
there are some problems happened.
the error information as below
![default](https://user-images.githubusercontent.com/33933620/44456984-91d58580-a634-11e8-9900-59ec1a5e1023.png)
Anyone could solve this problem?
Thanks a lot.

**Comment by cecileane** [comment]
Which version of Julia are you using? PhyloNetworks works with Julia v0.6 so far. Julia v0.7 and v1.0 have been release about 2 weeks ago, and Julia v0.1 is big change. We will update PhyloNetworks as soon as we can. In the meantime, you can install Julia v0.6 instead of the default Julia v0.1 — and please let us know if your problems persist with Julia v0.1.

**Comment by MeiyuanJi** [comment]
The version of julia
![default](https://user-images.githubusercontent.com/33933620/44509871-9148f780-a6e5-11e8-93c1-efc65bc79c50.png)
I will try with julia v0.1

**Comment by crsl4** [comment]
I think you should try with julia 0.6 (not 0.1). Because it won't work for julia 0.1, but we know that it should work for julia 0.6
Thanks!

**Comment by MeiyuanJi** [comment]
I tried with julia v0.6, the package "PhyloNetworks" is working right. However, it seems that it still has problem with PhyloPlots.
![default](https://user-images.githubusercontent.com/33933620/44558469-e4b75600-a776-11e8-9d2c-d9d25cabec23.png)
RCall error:
![default](https://user-images.githubusercontent.com/33933620/44558482-fef13400-a776-11e8-9eb8-38d3940b66de.png)
Are there some solution for this?
Thanks a lot.

**Comment by crsl4** [comment]
Can you try to update the packages first with `Pkg.update()`?
Maybe you also need to uninstall and install `RCall` again.

**Comment by cecileane** [comment]
These issues should be fixed with an update to Julia v1.0 and PhyloNetworks v0.9.0 (#90)
