### ISSUE TITLE
type of argument in calibrate function

### ISSUE THREAD

**Issue by crsl4** [crsl4/PhyloNetworks.jl#97]
Do we want the second argument in [calibrateFromPairwiseDistances!](https://github.com/crsl4/PhyloNetworks.jl/blob/8ec36e52788c250a45814de8b506deacb5ed3a6c/src/pairwiseDistanceLS.jl#L238) to be `Array{Union{Missing, Float64},2}` instead of `Array{Float64,2}` ? The reason is that if we save the pairwise distance matrix as a `DataFrame`, and then we read it again to use in the calibrate function, the object is now `Array{Union{Missing, Float64},2}`, so you get an error:

```
julia> df = CSV.read("genetreePairwiseDistance.csv");
julia> avD = Matrix(df);
julia> taxa = string.(names(df));
julia> calibrateFromPairwiseDistances!(tree, avD, taxa, forceMinorLength0=true, NLoptMethod=:LD_MMA, verbose=false)
ERROR: MethodError: no method matching calibrateFromPairwiseDistances!(::HybridNetwork, ::Array{Union{Missing, Float64},2}, ::Array{String,1}; forceMinorLength0=true, NLoptMethod=:LD_MMA, verbose=false)
```
What do you think, @pbastide ?

**Comment by crsl4** [comment]
Sorry, maybe we don't need it. I just found about the `avD = disallowmissing(Matrix(df));`

**Comment by cecileane** [comment]
`disallowmissing` was what I was looking for. It would be worth putting an example of it in the documentation.
