### ISSUE TITLE
running snaq kills julia

### ISSUE THREAD

**Issue by sandrahoffberg** [crsl4/PhyloNetworks.jl#99]
I am trying to run snaq! for the first time and getting an error.  
I can read the RAxML trees into Julia and I get the tableCF.txt and summaryTreesQuartets.txt tables.  My data consists of 3949 gene trees and 52360 4-taxon subsets.  I can input the starting tree (Astral output).  When I run the network analysis with 0 hybrid edges, within 10 seconds, it says "killed" and exits out of Julia.  Do you know what might be going wrong?  I appreciate your help!

My script is: 
`using PhyloNetworks;`
`raxmlCF = readTrees2CF("path/to/file.csv", writeTab=true, writeSummary=true)`
`tree = readTopology("path/to/file.tree")`
`net0= snaq!(tree, raxmlCF, hmax=0, filename="output/path/net0", seed=123)`

**Comment by cecileane** [comment]
Perhaps not enough RAM? Could you try on a subset of taxa? 35 taxa would take too long anyway, even if you managed to got enough memory (assuming memory is the problem here).
